const menuItems = [
  {
    name: "SALES",
    path: "/sales",
    submenu: [
      { name: "Men Sales", path: "/sales/men" },
      { name: "Women Sales", path: "/sales/women" },
      { name: "Kid Sale", path: "/sales/kids" },
      { name: "View All", path: "/sales/all" },
    ],
  },
  {
    name: "MEN",
    path: "/men",
    submenu: [
      {
        name: "Clothing",
        path: "/men/clothing",
        subsubmenu: [
          { name: "T-shirt", path: "/men/clothing/tshirt" },
          { name: "Shirt", path: "/men/clothing/shirt" },
          { name: "Pant", path: "/men/clothing/pant" },
          { name: "Sweatshirt", path: "/men/clothing/sweatshirt" },
          { name: "Leather", path: "/men/clothing/leather" },
          { name: "Coats & Jackets", path: "/men/clothing/coats-jackets" },
          { name: "Knitwear", path: "/men/clothing/knitwear" },
          { name: "Denim", path: "/men/clothing/denim" },
          { name: "Shorts", path: "/men/clothing/shorts" },
          { name: "Swimwear", path: "/men/clothing/swimwear" },
          { name: "Underwear & Socks", path: "/men/clothing/underwear-socks" },
          { name: "View All", path: "/men/alls" },
        ],
      },
      {
        name: "Shoes",
        path: "/men/shoes",
        subsubmenu: [
          { name: "Sneaker", path: "/men/shoes/Sneaker" },
          { name: "Out of Office", path: "/men/shoes/OutofOffice" },
          { name: "Be Right Back", path: "/men/shoes/BeRightBack" },
          { name: "Vulcanized", path: "/men/shoes/Vulcanized" },
          { name: "Boots", path: "/men/shoes/Boots" },
          { name: "Formal Shoes", path: "/men/shoes/FormalShoes" },
          { name: "Slides", path: "/men/shoes/Slides" },
          { name: "View All", path: "/men/shoes/ViewAll" },
        ],
      },
      {
        name: "Bags",
        path: "/men/bags",
        subsubmenu: [
          { name: "BackPacks", path: "/men/bags/BackPacks" },
          { name: "Crossbody bags", path: "/men/bags/Crossbodybags" },
          { name: "Tote bags", path: "/men/bags/Totebags" },
          { name: "Waist Bags and Clutches", path: "/men/bags/WaistBags" },
          { name: "View All", path: "/men/bags/ViewAll" },
        ],
      },
      {
        name: "Accessories",
        path: "/men/accessories",
        subsubmenu: [
          { name: "Hats and Scarves", path: "/men/accessories/Hatsand" },
          { name: "Wallet and Cardholders", path: "/men/accessories/Walletand" },
          { name: "Others Accessories", path: "/men/accessories/OthersAccessories" },
          { name: "View All", path: "/men/accessories/ViewAll" },
        ],
      },
      {
        name: "Jewelry",
        path: "/men/jewelry",
        subsubmenu: [
          { name: "Bracelets", path: "/men/jewelry/Bracelets" },
          { name: "Necklaces", path: "/men/jewelry/Necklaces" },
          { name: "Rings", path: "/men/jewelry/Rings" },
          { name: "Earrings", path: "/men/jewelry/Earrings" },
          { name: "View All", path: "/men/jewelry/ViewAll" },
        ],
      },
      { name: "View All", path: "/men/all" },
    ],
  },
  {
    name: "WOMEN",
    path: "/women",
    submenu: [
      {
        name: "Activewear",
        path: "/women/activewear",
        subsubmenu: [
          { name: "Tops & Bras", path: "/women/activewear/Tops&Bras" },
          { name: "Leggings", path: "/women/activewear/Leggings" },
          { name: "View All", path: "/women/activewear/ViewAll" },
        ],
      },
      {
        name: "Clothing",
        path: "/women/clothing",
        subsubmenu: [
          { name: "T-Shirts & Tops", path: "/women/clothing/Tops" },
          { name: "Knitwear", path: "/women/clothing/Knitwear" },
          { name: "Sweatshirts", path: "/women/clothing/Sweatshirts" },
          { name: "Dresses", path: "/women/clothing/Dresses" },
          { name: "Coat & Jackets", path: "/women/clothing/Cots&Jackets" },
          { name: "Leather", path: "/women/clothing/Leather" },
          { name: "Denim", path: "/women/clothing/Denim" },
          { name: "Pants", path: "/women/clothing/Pants" },
          { name: "Skirts", path: "/women/clothing/Skirts" },
          { name: "Shirts", path: "/women/clothing/Shirts" },
          { name: "Swimwear", path: "/women/clothing/Swimwear" },
          { name: "Underwear & Socks", path: "/women/clothing/Underwear" },
          { name: "View All", path: "/women/clothing/Viewall" },
        ],
      },
      {
        name: "Shoes",
        path: "/women/shoes",
        subsubmenu: [
          { name: "Sneakers", path: "/women/shoes/Sneakers" },
          { name: "Out of Office", path: "/women/shoes/OutofOffice" },
          { name: "Be Right Back", path: "/women/shoes/RightBack" },
          { name: "Vulcanized", path: "/women/shoes/Vulcanized" },
          { name: "Boots and Ankle Boots", path: "/women/shoes/Bootsand" },
          { name: "Mules and Pumps", path: "/women/shoes/Mules" },
          { name: "Sandals", path: "/women/shoes/Sandals" },
          { name: "Loafers and Flat Shoes ", path: "/women/shoes/Loafers" },
          { name: "Slides and Espadrillas", path: "/women/shoes/Slides" },
          { name: "View All", path: "/women/shoes/Viewall" },
        ],
      },
      {
        name: "Bags",
        path: "/women/bags",
        subsubmenu: [
          { name: "Shoulder Bags", path: "/women/bags/ShoulderBags" },
          { name: "Top handle Bags", path: "/women/bags/handleBags" },
          { name: "Tote Bags", path: "/women/bags/ToteBags" },
          { name: "Clutches and Pouches", path: "/women/bags/Pouches" },
          { name: "View All", path: "/women/bags/Viewall" },
        ],
      },
      {
        name: "Accessories",
        path: "/women/accessories",
        subsubmenu: [
          { name: "Wallet and Cardholders", path: "/women/accessories/Walletand" },
          { name: "Soft Accessories", path: "/women/accessories/SoftAccessories" },
          { name: "Belts", path: "/women/accessories/Belts" },
          { name: "View All", path: "/women/accessories/Viewall" },
        ],
      },
      {
        name: "Jewelry",
        path: "/women/jewelry",
        subsubmenu: [
          { name: "Bracelets", path: "/women/jewelry/Bracelets" },
          { name: "Necklaces", path: "/women/jewelry/Necklaces" },
          { name: "Rings", path: "/women/jewelry/Rings" },
          { name: "Earrings", path: "/women/jewelry/Earrings" },
          { name: "View All", path: "/women/jewelry/ViewAll" },
        ],
      },
      { name: "View All", path: "/women/all" },
    ],
  },
  {
    name: "KIDS",
    path: "/kids",
    submenu: [
      {
        name: "Boys",
        path: "/kids/boys",
        subsubmenu: [
          { name: "Boy,s Clothing", path: "/kids/boys/Clothing" },
          { name: "Boy,s Shoes", path: "/kids/boys/Shoes" },
          { name: "Boy,s Accessories ", path: "/kids/boys/Accessories" },
          { name: "View All", path: "/kids/boys/ViewAll" },
        ],
      },
      {
        name: "Girls",
        path: "/kids/girls",
        subsubmenu: [
          { name: "Girl,s Clothing", path: "/kids/girls/Clothing" },
          { name: "Girl,s Shoes", path: "/kids/girls/Shoes" },
          { name: "Girl,s Accessories ", path: "/kids/girls/Accessories" },
          { name: "View All", path: "/kids/girls/ViewAll" },
        ],
      },
      { name: "Baby", path: "/kids/baby" },
      { name: "View All", path: "/kids/all" },
    ],
  },
  {
    name: "EYEWEAR",
    path: "/eyewear",
    submenu: [
      { name: "Sunglasses", path: "/eyewear/sunglasses" },
      { name: "Eyeglass", path: "/eyewear/eyeglass" },
      { name: "View All", path: "/eyewear/all" },
    ],
  },
  {
    name: "ICONS",
    path: "/icons",
    submenu: [
      { name: "Men's Icon", path: "/icons/men" },
      { name: "Women's Icon", path: "/icons/women" },
    ],
  },
  {
    name: "SPECIAL COLLECTION",
    path: "/special-collection",
    submenu: [
      { name: "Fall", path: "/special-collection/fall" },
      { name: "Winter", path: "/special-collection/winter" },
      { name: "Fresco", path: "/special-collection/fresco" },
    ],
  },
  { name: "BRAND", path: "/brand" },
  { name: "Login", path: "/login" },
  { name: "Wishlist", path: "/wishlist" },
];